### ISSUE TITLE
index.html not refreshing 

### ISSUE THREAD

**Issue by glenosAU** [dcapslock/weewx-responsive-skin#14]
I am having a problem with aussearch.py and the responsive skin. index.html had stopped updating and I assumed it was due to Issues #12 and #13 so I updated aussearch.py. However, index.html is still not updating except for the graphs produced by weewx. It appears the week, month and year pages are not affected.

` $ service status weewx`

gives the following output:

> Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/aussearch.py", line 385, in __getattr__

> Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: ****      if self.root is not None:

> Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: ****    [Previous line repeated 489 more times]

> Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: ****    File "/usr/share/weewx/user/aussearch.py", line 382, in __getattr__

> Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: ****      syslog.syslog(syslog.LOG_ERR, "aussearch: cannot download xml file %s: %s" % (self.xml_file, e))

> Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: ****  RecursionError: maximum recursion depth exceeded in comparison

> Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] INFO weewx.cheetahgenerator: Generated 9 files for report ResponsiveReport in 3.85 seconds

> Jun 13 08:11:08 Napsberrypi python3[551]: weewx[551] INFO weewx.imagegenerator: Generated 13 images for report ResponsiveReport in 1.20 seconds

> Jun 13 08:11:08 Napsberrypi python3[551]: weewx[551] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx

> Jun 13 08:11:18 Napsberrypi python3[551]: weewx[551] INFO weewx.reportengine: ftpgenerator: Ftp'd 22 files in 9.93 seconds

As I understand line 385 is failing, that is  
```
        if self.root is not None:            
                 self.root_node = XMLNode(self.root)
```
When I run `$ sudo wee_reports /etc/weewx/weewx.conf` it runs normally and index.html is refreshed with 11 files and 13 images generated by weewx. The really weird bit is the daemon runs normally on the next scheduled generation as well but not after that.

**Comment by dcapslock** [comment]
Hi. Looks like you still need to restart weewx. The fact wee_reports is running fine is a good sign all is fixed, but weewx will be running with compiled/cache version of the code until restarted.

________________________________
From: glenosAU ***@***.***>
Sent: Sunday, June 13, 2021 8:50:10 AM
To: dcapslock/weewx-responsive-skin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dcapslock/weewx-responsive-skin] index.html not refreshing (#14)


I am having a problem with aussearch.py and the responsive skin. index.html had stopped updating and I assumed it was due to Issues #12<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdcapslock%2Fweewx-responsive-skin%2Fissues%2F12&data=04%7C01%7C%7C37303a45250a4fee9d2908d92df46f20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637591350121682736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UqcRG7GVPVW%2BwuL39zsjSaEgsaieQ7MLH%2BHc6pot%2FO4%3D&reserved=0> and #13<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdcapslock%2Fweewx-responsive-skin%2Fissues%2F13&data=04%7C01%7C%7C37303a45250a4fee9d2908d92df46f20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637591350121692730%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qHRz9MylyFzEz01%2FyNmTMnKi0fa4CRZGIFX3R9XHaRk%3D&reserved=0> so I updated aussearch.py. However, index.html is still not updating except for the graphs produced by weewx. It appears the week, month and year pages are not affected.

$ service status weewx

gives the following output:

Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: **** File "/usr/share/weewx/user/aussearch.py", line 385, in getattr

Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: **** if self.root is not None:

Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: **** [Previous line repeated 489 more times]

Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: **** File "/usr/share/weewx/user/aussearch.py", line 382, in getattr

Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: **** syslog.syslog(syslog.LOG_ERR, "aussearch: cannot download xml file %s: %s" % (self.xml_file, e))

Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] ERROR weewx.cheetahgenerator: **** RecursionError: maximum recursion depth exceeded in comparison

Jun 13 08:11:07 Napsberrypi python3[551]: weewx[551] INFO weewx.cheetahgenerator: Generated 9 files for report ResponsiveReport in 3.85 seconds

Jun 13 08:11:08 Napsberrypi python3[551]: weewx[551] INFO weewx.imagegenerator: Generated 13 images for report ResponsiveReport in 1.20 seconds

Jun 13 08:11:08 Napsberrypi python3[551]: weewx[551] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx

Jun 13 08:11:18 Napsberrypi python3[551]: weewx[551] INFO weewx.reportengine: ftpgenerator: Ftp'd 22 files in 9.93 seconds

As I understand line 385 is failing, that is

        if self.root is not None:
                 self.root_node = XMLNode(self.root)


When I run $ sudo wee_reports /etc/weewx/weewx.conf it runs normally and index.html is refreshed with 11 files and 13 images generated by weewx. The really weird bit is the daemon runs normally on the next scheduled generation as well but not after that.

**Comment by glenosAU** [comment]
Doh!
That fixed it.
